
project_id = "rjqrzhjvjgfwgowlsvfw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[[db.publications]]
name = "public"
publish_insert = true
publish_update = true
publish_delete = true
publish_truncate = true

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
port = 54323
enabled = true

[inbucket]
enabled = true
port = 54324
max_size = "10MB"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
[functions]
[functions.generate-slug]
verify_jwt = true
