// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjqrzhjvjgfhgowlsvlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcXJ6aGp2amdmaGdvd2xzdmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODMyNTQsImV4cCI6MjA2MDU1OTI1NH0.1LXnucd5WuB3XAYkVmrrE65SM0USQQ1OvZXiMLmt6W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);